### ISSUE TITLE
How to use with "next-compose-plugins"

### ISSUE THREAD

**Issue by muzlevy** [uiwjs/next-remove-imports#10]
hello, I would like to know if they can be used together

This is my next.config.js

    const withPlugins = require("next-compose-plugins");
    const withImages = require("next-images");
    const withLess = require("next-with-less");
    const withTM = require("next-transpile-modules")([
      "jotai",
      "yup",
      "overlayscrollbars",
      "overlayscrollbars-react",
      "react-hook-form"
    ]);
    module.exports = withPlugins([withTM, withImages, withLess], {
      images: {
      disableStaticImages: true,
      },
      webpack: (config, options) => {
      return config;
      },
    });

**Comment by jaywcjlove** [comment]
@muzlevy https://github.com/uiwjs/next-remove-imports/tree/main/example

**Comment by muzlevy** [comment]
> @muzlevy https://github.com/uiwjs/next-remove-imports/tree/main/example

Thank you for your answer, I've already solved this problem

**Comment by GaNiziolek** [comment]
@muzlevy can you share with us how you solve this?

**Comment by muzlevy** [comment]
> @muzlevy can you share with us how you solve this?

I use spread syntax

```
const withPlugins = require("next-compose-plugins");
const removeImports = require("next-remove-imports");

module.exports = withPlugins([withTM, withImages], {
  images: {
    disableStaticImages: true,
  },
  webpack: (config, options) => {
    return config;
  },
  ...removeImports({
    test: /node_modules([\s\S]*?)\.(tsx|ts|js|mjs|jsx)$/,
    matchImports: "\\.(less|css|scss|sass|styl)$",
  }),
});
```
