### ISSUE TITLE
Failed Synk vulnerability check

### ISSUE THREAD

**Issue by DhiraPT** [uiwjs/next-remove-imports#12]
Issues with no direct upgrade or patch:
  ✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795] in semver@7.3.8
    introduced by next-remove-imports@1.0.11 > @babel/core@7.22.5 > semver@6.3.0 and 4 other path(s)
  This issue was fixed in versions: 5.7.2, 6.3.1, 7.5.2

**Comment by jaywcjlove** [comment]
@DhiraPT what do I need to do?

**Comment by DhiraPT** [comment]
> @DhiraPT what do I need to do?

Upgrade @babel/core to the latest version

**Comment by jaywcjlove** [comment]
@DhiraPT Upgrade `v1.0.12`
